name: Build and deploy Node.js app to Azure Web App - foodcheck-web

on:
  push:
    branches:
      - web-deployment
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Liste des fichiers pour vérifier si le dossier api-food-check existe
      - name: List files in the repository
        run: ls -R

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          ls
          cd api-food-check  # Naviguer dans le dossier contenant package.json
          npm install
          npm run start --if-present
         
      - name: Zip artifact for deployment
        run: |
          cd api-food-check  # Assurez-vous d'être dans le bon répertoire
          zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: api-food-check/release.zip
